// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ddmandptdqdigxsbbfcj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRkbWFuZHB0ZHFkaWd4c2JiZmNqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Mzk0NzM1OTMsImV4cCI6MjA1NTA0OTU5M30.Ub50TfsYCrjpQFnD9S1U4kPZHVY2mKoif4MK8C_feO0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);